# Generated by Django 2.2 on 2021-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraBoards',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('id', models.CharField(db_column='ID', max_length=15, primary_key=True, serialize=False)),
                ('proj_id', models.IntegerField(blank=True)),
                ('proj_key', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'jira_board',
            },
        ),
        migrations.CreateModel(
            name='JiraFixVersions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('id', models.CharField(db_column='ID', help_text='版本id', max_length=15, primary_key=True, serialize=False, verbose_name='版本id')),
                ('name', models.CharField(help_text='版本名称', max_length=255, verbose_name='版本名称')),
                ('proj_id', models.CharField(blank=True, help_text='关联的项目id', max_length=255, verbose_name='关联的项目id')),
                ('proj_key', models.CharField(blank=True, help_text='关联的项目前缀', max_length=255, verbose_name='关联的项目前缀')),
                ('sprint_id', models.CharField(blank=True, help_text='关联的迭代id', max_length=255, null=True, verbose_name='关联的迭代id')),
                ('start_date', models.DateTimeField(blank=True, help_text='开始时间', null=True, verbose_name='开始时间')),
                ('release_date', models.DateTimeField(blank=True, help_text='发版时间', null=True, verbose_name='发版时间')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jira_fixversion',
            },
        ),
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('id', models.CharField(db_column='ID', help_text='issueid', max_length=255, primary_key=True, serialize=False, verbose_name='issueid')),
                ('key', models.CharField(blank=True, help_text='issue编号', max_length=255, verbose_name='issue编号')),
                ('type', models.CharField(blank=True, help_text='issue类型', max_length=255, verbose_name='issue类型')),
                ('proj_id', models.IntegerField(blank=True, help_text='关联的项目id', verbose_name='关联的项目id')),
                ('proj_key', models.CharField(blank=True, help_text='关联的项目前缀', max_length=255, verbose_name='关联的项目前缀')),
                ('resolution', models.CharField(blank=True, help_text='解决结果', max_length=255, verbose_name='解决结果')),
                ('resolution_date', models.DateTimeField(blank=True, help_text='解决日期', null=True, verbose_name='解决日期')),
                ('priority', models.CharField(blank=True, help_text='优先级', max_length=10, null=True, verbose_name='优先级')),
                ('assignee', models.CharField(blank=True, help_text='指派人', max_length=255, null=True, verbose_name='指派人')),
                ('created', models.CharField(blank=True, help_text='创建时间', max_length=255, verbose_name='创建时间')),
                ('updated', models.DateTimeField(blank=True, help_text='更新时间', verbose_name='更新时间')),
                ('status', models.CharField(blank=True, help_text='issue状态', max_length=255, null=True, verbose_name='issue状态')),
                ('summary', models.CharField(blank=True, help_text='issue标题', max_length=255, null=True, verbose_name='issue标题')),
                ('description', models.TextField(blank=True, help_text='issue描述', null=True, verbose_name='issue描述')),
                ('creator', models.CharField(blank=True, help_text='issue创建者', max_length=255, verbose_name='issue创建者')),
                ('original_time_estimate', models.IntegerField(blank=True, help_text='估时', null=True, verbose_name='估时')),
                ('bugOwner', models.CharField(blank=True, help_text='bugOwner', max_length=255, null=True, verbose_name='bugOwner')),
                ('env', models.CharField(blank=True, help_text='测试环境', max_length=255, null=True, verbose_name='测试环境')),
                ('platform', models.CharField(blank=True, help_text='issue所属端/平台', max_length=255, null=True, verbose_name='issue所属端/平台')),
                ('bug_level', models.CharField(blank=True, help_text='bug等级-线上/线下', max_length=255, null=True, verbose_name='bug等级-线上/线下')),
                ('sub_bug_level', models.CharField(blank=True, help_text='bug子等级-S0/1/2/3', max_length=255, null=True, verbose_name='bug子等级-S0/1/2/3')),
                ('fix_version', models.CharField(blank=True, help_text='修复的版本', max_length=255, null=True, verbose_name='修复的版本')),
                ('target_start', models.DateTimeField(help_text='目标开始时间', null=True, verbose_name='目标开始时间')),
                ('target_end', models.DateTimeField(help_text='目标结束时间', null=True, verbose_name='目标结束时间')),
                ('issue_links', models.TextField(help_text='关联issue', max_length=65535, null=True, verbose_name='关联issue')),
                ('parent_key', models.CharField(blank=True, help_text='修复的版本', max_length=255, null=True, verbose_name='修复的版本')),
                ('sprint_id', models.CharField(help_text='所属sprint', max_length=255, null=True, verbose_name='所属sprint')),
                ('epic_key', models.CharField(help_text='所属epic', max_length=255, null=True, verbose_name='所属epic')),
                ('fix_time', models.IntegerField(blank=True, help_text='解决时长(s)', null=True, verbose_name='解决时长(s)')),
                ('close_time', models.IntegerField(blank=True, help_text='关闭时长(s)', null=True, verbose_name='关闭时长(s)')),
                ('reopen_count', models.IntegerField(blank=True, help_text='reopen次数', null=True, verbose_name='reopen次数')),
            ],
            options={
                'db_table': 'jira_issue',
            },
        ),
        migrations.CreateModel(
            name='JiraProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('lead', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jira_project',
            },
        ),
        migrations.CreateModel(
            name='JiraSprint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('id', models.CharField(help_text='sprintid', max_length=15, primary_key=True, serialize=False, verbose_name='sprintid')),
                ('name', models.CharField(help_text='迭代名称', max_length=255, verbose_name='迭代名称')),
                ('board_id', models.IntegerField(help_text='关联看板id', verbose_name='关联看板id')),
                ('proj_id', models.CharField(blank=True, help_text='关联的项目id', max_length=255, verbose_name='关联的项目id')),
                ('proj_key', models.CharField(blank=True, help_text='关联的项目前缀', max_length=255, verbose_name='关联的项目前缀')),
                ('goal', models.TextField(blank=True, help_text='目标', null=True, verbose_name='目标')),
                ('end_date', models.DateField(blank=True, help_text='结束时间', null=True, verbose_name='结束时间')),
                ('closed', models.IntegerField(help_text='关闭标识', verbose_name='关闭标识')),
                ('complete_date', models.DateField(blank=True, help_text='完成时间', null=True, verbose_name='完成时间')),
                ('started', models.IntegerField(help_text='开始标识', verbose_name='开始标识')),
                ('start_date', models.DateField(blank=True, help_text='开始时间', null=True, verbose_name='开始时间')),
            ],
            options={
                'db_table': 'jira_sprint',
            },
        ),
        migrations.CreateModel(
            name='JiraBusinessCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('project_id', models.CharField(max_length=20, verbose_name='项目id')),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('delivery_cycle', models.FloatField(null=True, verbose_name='交付周期')),
                ('develop_cycle', models.FloatField(null=True, verbose_name='开发交付周期')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(verbose_name='截止时间')),
            ],
            options={
                'db_table': 'jira_business_cycle',
                'unique_together': {('project_id', 'end_date')},
            },
        ),
    ]
