# Generated by Django 2.2 on 2021-09-15 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSsoAccessToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('uid', models.CharField(help_text='sso user uid', max_length=60, primary_key=True, serialize=False, verbose_name='sso user uid')),
                ('access_token', models.CharField(help_text='sso access_token', max_length=60, verbose_name='sso access_token')),
                ('expire_time', models.IntegerField(help_text='过期时间', verbose_name='过期时间')),
            ],
            options={
                'db_table': 'sso_access_token',
            },
        ),
        migrations.CreateModel(
            name='UserAuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_groups',
            },
        ),
    ]
