# Generated by Django 2.2 on 2021-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloOperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('appId', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=64, null=True)),
                ('value', models.TextField(null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('operator', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'apollo_operate_log',
            },
        ),
        migrations.CreateModel(
            name='ApolloAppItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('appId', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=64)),
                ('dataChangeLastModifiedBy', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'apollo_app_items',
                'unique_together': {('appId', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ApolloAppChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('app_id', models.CharField(max_length=64)),
                ('chat_id', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'apollo_app_chat',
                'unique_together': {('app_id', 'chat_id')},
            },
        ),
    ]
