# Generated by Django 2.2 on 2021-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCaseRunHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('auto_config_id', models.CharField(help_text='自动化用例配置集id', max_length=32)),
                ('auto_config_name', models.CharField(help_text='自动化用例配置集名称', max_length=64)),
                ('username', models.CharField(default='system', help_text='触发者', max_length=32)),
                ('build_number', models.IntegerField(help_text='jenkins构建number', null=True)),
                ('recover_times', models.IntegerField(default=0, help_text='重试次数')),
                ('status', models.CharField(default='pending', help_text='执行状态', max_length=8)),
                ('mark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'auto_case_run_history',
            },
        ),
        migrations.CreateModel(
            name='AutoCaseTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='上次修改时间', verbose_name='上次修改时间')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'auto_case_tags',
            },
        ),
    ]
